export const KNOWN_PEOPLE = [
  "Avi",
  "Batya",
  "David",
  "Babi-Iancu",
  "Babi",
  "Iancu",
  "Yehudah",
  "Yehudit",
  "Elisabeth Bura",
  "Mema",
  "Paul",
  "Morgan",
  "Robert",
  "Sharon",
  "Tara",
  "Rabbi Malin",
  "R' Malin",
  "Rav Waxman",
  "R' Sheinberg",
  "Moishe",
  "Basi",
];

export const KNOWN_LOCATIONS = [
  "Israel",
  "Kotel",
  "Ein Gedi",
  "Massada",
  "Dead Sea",
  "Chelsea Piers",
  "Deal NJ",
  "Deal, NJ",
  "Mt Scopus",
  "Har HaZeisim",
  "Meah Shearim",
  "Tzefat",
  "Amuka",
  "Meron",
  "Tiveria",
  "Rosh Hanikra",
  "Acco",
  "Tel Aviv",
  "Bronx Zoo",
  "Puerto Rico",
  "Florida",
  "EPCOT",
  "Universal",
  "Shaalvim",
  "Yad Vashem",
  "Golan",
  "Cardo",
  "Shaar Yaffo",
];

export const KNOWN_EVENTS = [
  "Succot",
  "Chanuka",
  "Chanukah",
  "Purim",
  "Pesach",
  "Graduation",
  "Bris",
  "Upshiring",
  "Upsheiring",
  "Bar Mitzvah",
  "Karate",
  "Gymnastics",
  "Camp",
  "Siddur Party",
  "Chumash Party",
  "Vach Nacht",
  "Shoah",
  "Simchat Beit Hashoeva",
  "Simchas Bais Hashoeva",
  "Slichos",
  "Yom Kippur",
];

export const MEDIA_EXTENSIONS = {
  photo: new Set([".jpg", ".jpeg", ".png", ".tif", ".tiff", ".gif", ".heic", ".webp"]),
  video: new Set([".mp4", ".mov", ".avi", ".mkv", ".webm"]),
};

export const SKIP_EXTENSIONS = new Set([
  ".db",
  ".html",
  ".htm",
  ".css",
  ".js",
  ".wav",
  ".woff",
  ".ttf",
  ".eot",
]);

export const SKIP_FILES = new Set([".DS_Store", "Thumbs.db", "desktop.ini"]);
